spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowed-origins: "http://localhost:4200"
            allowed-methods: "GET, POST, PUT, DELETE, OPTIONS"
            allowed-headers: "*"
            allow-credentials: true
            exposed-headers: "Authorization, Content-Disposition"
            max-age: 3600